### PR TITLE
Modernization: namespaces, psr-4 autoloading, formatting

### LINKED ISSUE #17: 2015 - isn't it time yet to use autoloaders?
Really hard to add this library to code, built with using autoloading. All those 'require' looks archaic and calling code doesn't know and shouldn't know folders structure of this library.

### PR DESCRIPTION
**Pull request by hackel**
I pulled in changes from the various forks of this project and applied them on top of the current master.  I then added some more changes of my own to try to make this library usable in a modern project.  I have deployed this successfully to verify addresses in a Laravel 5 application.

So far I have only tested the Address Verifier!  I haven't changed any actual functionality, so I think that everything else should work, but can't make any promises.  It does need to be tested.  Unit tests would be great at some point, but this is at least a start in the right direction.  I would merge this to a separate branch.  

This should (finally!) fix #17.

### CODE REVIEW

**Comment by VinceG** [comment]
@hackel Damn, that's a great PR. bare with me while i test this whole thing prior to releasing it. i'll also add this repository to packagist. 

Thanks a lot for the help.

**Comment by hackel** [comment]
No problem, I mostly just collected the work of others and moved some files around.  Not sure why @kytart 's contributions aren't being attributed to him, but he's in there as well!

**Comment by jakebathman** [comment]
Good stuff. I have some modifications to the Address Verify stuff that I was going to submit a pull request for, but I'll wait for this to go through and fork the updated version.

**Comment by cdtweb** [comment]
ETA on releasing this?

**Comment by VinceG** [comment]
@hackel thank you. merged.

**Pull request merged**
